version: '3.8'

services:
  db:
    image: postgres:alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: nn_demo_development
    container_name: nn-demo_db

  api:
    build: .
    command: sh -c 'rm -f tmp/pids/server.pid && rails s -b 0.0.0.0'
    volumes:
      - .:/nn-demo
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:password@db
      REDIS_URL: redis://redis
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    container_name: nn-demo_api

  redis:
    image: redis:alpine
    container_name: nn-demo_redis

  worker:
    build: .
    command: sidekiq
    volumes:
      - .:/nn-demo
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:password@db
      REDIS_URL: redis://redis
    tty: true
    stdin_open: true
    container_name: nn-demo_worker

volumes:
  db:
